version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Build
          command: yarn build

      - persist_to_workspace:
          root: ~/code
          paths:
            - .

  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/node:8.11.1
    steps:
      - attach_workspace:
          at: ~/code
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: renewal
