version: 2

defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:8.11.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install npm packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Build
          command: yarn build

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - add_ssh_keys:
          fingerprints:
            - "16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48"

      - run:
          name: Deploy
          command: |
            git config --global user.email "ishikura.noboru@gmail.com"
            git config --global user.name "noboru-i"
            yarn deploy

  create_article:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Fetch issue and create article
          command: yarn run fetch_issue
      - run:
          name: Push article
          command: |
            git config --global user.email "ishikura.noboru@gmail.com"
            git config --global user.name "noboru-i"
            git add src/pages/articles/
            git commit -m 'create article'
            git push origin src:src

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: src

  nightly:
    triggers:
      - schedule:
          cron: "0 17 * * 5"
          filters:
            branches:
              only:
                - src
    jobs:
      - build
      - create_article:
          requires:
            - build
      - deploy:
          requires:
            - create_article
